const eventTypes = {
    SET_SITE_DATA: "SET_SITE_DATA",
    GET_EVENTS_OK: "GET_EVENTS_OK",
    GET_USER_EVENTS_OK: "GET_USER_EVENTS_OK",
    ADD_EVENT_TO_LIST: "ADD_EVENT_TO_LIST",
    REMOVE_EVENT: "REMOVE_EVENT"
}

export default eventTypes;