const userTypes = {
    SET_USER: "SET_USER",
    SET_USER_ROLES: "SET_USER_ROLES",

    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
    UPDATE_FROM_LOCAL: "UPDATE_FROM_LOCAL",
    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_CONTACT: "UPDATE_USER_CONTACT",
    GET_BUSINESS_ROLES: "GET_BUSINESS_ROLES",
    GET_PENDING_REQUEST_OK: "GET_PENDING_REQUEST_OK",
    USER_LOGOUT: "USER_LOGOUT"
}

export default userTypes;